---
- name: Install and start apache
  hosts: all
  become: true

  tasks:
  - name: Example clone of a single branch
    ansible.builtin.git:
      repo: https://github.com/Adbonino/ansible_test.git
      dest: ./ansible-examples
      single_branch: yes
      version: master
