---
- name: Install and start apache
  hosts: all
  become: true

  tasks:
    - name: Ensure the git package is intalled
      ansible.builtin.yum:
        name: git
        state: present

    - name: Example clone of a single branch
      ansible.builtin.git:
        repo: https://github.com/Adbonino/ansible_test.git
        dest: ./ansible-examples
        single_branch: yes
        version: main
