- name: Install community general collection in localhost
  hosts: all

  tasks:
  - name: Install collection community.network
    community.general.ansible_galaxy_install:
      type: collection
      name: community.general
